### ISSUE TITLE
Create rules

### ISSUE THREAD

**Issue by mayuso** [fuzzylite/jfuzzylite#3]
Hello, I have been searching for a Fuzzy Logic related Java project and found this. 

Can I use this API to create rules giving it some data?

Thank you in advance.

**Comment by mayuso** [comment]
Just wanted to add a some extra details: 
I have my data stored in about 10 excels (and growing each week), each of these has 4k rows and 55 columns.
I have trouble with this API, I can´t really understand it well. 
What kind of data format does this API use? And still, I am interested in creating rules, is it possible?

**Comment by jcrada** [comment]
Hi, currently jfuzzylite does not provide such a functionality.

**Comment by mayuso** [comment]
Ok, many thanks! I will follow this project :) I hope I can help you guys with anything.
