### ISSUE TITLE
Probabilities of Mandani FIS output terms

### ISSUE THREAD

**Issue by bbrighttaer** [fuzzylite/jfuzzylite#8]
Hello Dr, 
first of all, thanks a lot for your wonderful work on jfuzzylite. It has really helped me a lot in my project. I have realized that the probabilities of the output for the terms of an output variable does not always add up to 1 and I would want you to assist me with a clarification on that.
Thanks.

**Comment by jcrada** [comment]
Hi, thank you for your post. For help, could you please post your questions in the forums at fuzzylite.com/forums? Thanks.

**Comment by bbrighttaer** [comment]
okay, I will do that right away. Thanks!
